# my zshrc file
source $HOME/dotfiles/dots/export.zsh

# -------
# Aliases
# -------
alias H="history"
alias lgrep="ls|grep $1"
alias hgrep="history|grep -n2 $1"
alias trew="tmux rename-window $1"
alias tres="tmux rename-session $1"
alias cdd="cd $DOTHOME"
alias cddf="cd $DOTDOTS"
alias cddm="cd $DOTMODS"
alias rezshrc='source ~/.zshrc'

source $DOTDOTS/util.zsh

# --------------------
# APPLICATION SPECIFIC
# --------------------
if which pass > $DEVNULL; then
    export PASSWORD_STORE_DIR=$HOME/.password-store
    # compinit /usr/local/Cellar/pass/1.7.1/share/zsh/site-functions/_pass
fi

if which cmus > $DEVNULL; then
    # bc OSX has an irritating warning related to soudn library
    alias cmus="/usr/local/bin/cmus 2>/dev/null"
fi

# ---
# ZSH
# ---
bindkey ^P up-line-or-search
unsetopt correct
fpath+=$DOTMODS/zsh/zsh-completions
fpath+=$DOTMODS/zsh/spaceship-prompt/spaceship.zsh
CASE_SENSITIVE="true"
setopt EXTENDED_HISTORY
plugins=(git colored-man-pages)
DISABLE_AUTO_UPDATE=true
ZSH_THEME="jispwoso"
export DISPLAY=:0.0
source $ZSH/oh-my-zsh.sh
source $DOTMODS/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

# cute little welcome banner
echo $magenta"m"$green"g"$cyan"c"$blue"b"$white"w"$red"r"$yellow"y$default"
echo ""
echo " $magenta`date`"$default
echo "      running "`uname -a`
echo ""

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Set Spaceship ZSH as a prompt
fpath=($fpath "/home/$USER/.zfunctions")
autoload -U promptinit; promptinit
prompt spaceship
fpath=($fpath "/home/padams/.zfunctions")
