# my zshrc file

# ---
# ZSH
# ---
CASE_SENSITIVE="true"
setopt EXTENDED_HISTORY
plugins=(git colored-man-pages)
DISABLE_AUTO_UPDATE=true
source $ZSH/oh-my-zsh.sh
source $DOTMODS/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
bindkey "^P" up-line-or-search
unsetopt correct
fpath+=/usr/local/share/zsh-completions

# ------
# SOURCE
# ------
source $DOTDOTS/aliases.zsh
source $DOTDOTS/util.zsh
source $DOTDOTS/platform.zsh
source $DOTDOTS/applications.zsh

# cute little welcome banner
echo $magenta"m"$green"g"$cyan"c"$blue"b"$white"w"$red"r"$yellow"y$default"
echo ""
echo " $magenta`date`"$default
echo "      "$USERNAME'@'`hostname`", running `uname`"
echo ""
# screenfetch -t
