directory: ~/music/beets

library: ~/.config/beets/musiclibrary.blb

import:
    move: no

pluginpath: [/Users/paul/anaconda2/lib/python2.7/site-packages/beets/]

plugins: edit

edit:
    itemfields: track title album artist composer albumartist
